name: Gamlendar Game Notification Workflow

on:
  
  workflow_dispatch: # 수동 실행
  schedule:
    - cron: "0 0 * * *" # 매일 오전 9시 실행
  

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      # 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # Python 설치
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Wireguard
        run: |
          sudo apt-get update
          sudo apt install wireguard

      - name: Initialize secrets key
        run: |
          echo "${{ secrets.WIREGUARD_PRIVATE_KEY }}" > privatekey
          echo "${{ secrets.WIREGUARD_PUBLIC_KEY }}" > publickey
          echo "${{ secrets.WIREGUARD_ENDPOINT }}" > wg_endpoint
          echo "${{ secrets.WIREGUARD_IP_ADDRESS }}" > wg_ipAddress
          echo "${{ secrets.WIREGUARD_GATEWAY }}" > wg_gateway

      - name: Setup Wireguard
        run: |
          sudo ip link add dev wg0 type wireguard
          sudo ip address add dev wg0 wg_ipAddress peer wg_gateway

          sudo wg set wg0 listen-port 48123 private-key privatekey peer publickey allowed-ips 0.0.0.0/0 endpoint wg_endpoint
        
          sudo ip link set up dev wg0


      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "serviceAccountKey.json"
          json: ${{ secrets.SERVICE_ACCOUNT_KEY }}


      - name: wait 10 sec
        run: |
          sleep 10

      # main.py 실행
      - name: Run Python script
        env:
          REDIS_CACHE_HOST: ${{secrets.REDIS_CACHE_HOST}}
          REDIS_CACHE_PORT: ${{secrets.REDIS_CACHE_PORT}}
          REDIS_PASSWORD: ${{secrets.REDIS_PASSWORD}}
        
        run: |
          python main.py

      - name: Remove serviceAccountKey
        run: rm -rf serviceAccountKey.json
